version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.15.4
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - "**/*"
  base-directory: "dist"
